import json

km_file = r'c:\xampp\htdocs\sana_project\Final_Project\NTTI_Teacher_Attendent\ntti-attendance\lang\km.json'

with open(km_file, 'r', encoding='utf-8') as f:
    translations = json.load(f)

system_wide_km = {
    "Dashboard": "ផ្ទាំងគ្រប់គ្រង",
    "Scan Station": "ស្ថានីយស្កែន",
    "Teacher Directory": "បញ្ជីឈ្មោះគ្រូបង្រៀន",
    "RFID Cards": "កាត RFID",
    "Departments": "ដេប៉ាតឺម៉ង់",
    "Leave Requests": "សំណើសុំច្បាប់",
    "Schedules": "កាលវិភាគ",
    "Analytics": "ការវិភាគ",
    "Reports": "របាយការណ៍",
    "Security Logs": "កំណត់ត្រាសុវត្ថិភាព",
    "Settings": "ការកំណត់",
    "Search anything...": "ស្វែងរកអ្វីមួយ...",
    "Scanner Online": "ម៉ាស៊ីនស្កែនដំណើរការ",
    "Scanner Offline": "ម៉ាស៊ីនស្កែនដាច់ការភ្ជាប់",
    "Checking...": "កំពុងពិនិត្យ...",
    "Link Lost": "បាត់បង់ការភ្ជាប់",
    "LIVE MONITOR": "ការតាមដានផ្ទាល់",
    "TEACHER PORTAL": "ច្រកទ្វារគ្រូបង្រៀន",
    "Institutional Timetable System": "ប្រព័ន្ធកាលវិភាគស្ថាប័ន",
    "Teaching Timetables & Schedules": "កាលវិភាគបង្រៀន",
    "Manage class schedules, subject allocations, and teacher room assignments.": "គ្រប់គ្រងកាលវិភាគថ្នាក់ មុខវិជ្ជា និងការបែងចែកបន្ទប់បង្រៀន។",
    "Add Teaching Slot": "បន្ថែមម៉ោងបង្រៀន",
    "Total Weekly Classes": "ថ្នាក់បង្រៀនសរុបក្នុងមួយសប្តាហ៍",
    "Active Instructors": "គ្រូបង្រៀនសកម្ម",
    "Assigned Rooms": "បន្ទប់បង្រៀនដែលបានចាត់តាំង",
    "Active Days": "ថ្ងៃបង្រៀនសកម្ម",
    "All Days": "គ្រប់ថ្ងៃ",
    "Search subject, room, teacher...": "ស្វែងរកមុខវិជ្ជា បន្ទប់ គ្រូបង្រៀន...",
    "Slots": "ម៉ោង",
    "Delete Slot": "លុបម៉ោងបង្រៀន",
    "Delete this slot?": "តើអ្នកប្រាកដជាចង់លុបម៉ោងបង្រៀននេះមែនទេ?",
    "No classes scheduled": "គ្មានថ្នាក់បង្រៀនទេ",
    "Teacher": "គ្រូបង្រៀន",
    "Day of Week": "ថ្ងៃនៃសប្តាហ៍",
    "Room Number": "លេខបន្ទប់",
    "Start Time": "ម៉ោងចាប់ផ្ដើម",
    "End Time": "ម៉ោងបញ្ចប់",
    "Subject / Class Name": "ឈ្មោះមុខវិជ្ជា / ថ្នាក់",
    "Save Slot": "រក្សាទុកម៉ោងបង្រៀន",
    "Cancel": "បោះបង់",
    "Monday": "ច័ន្ទ",
    "Tuesday": "អង្គារ",
    "Wednesday": "ពុធ",
    "Thursday": "ព្រហស្បតិ៍",
    "Friday": "សុក្រ",
    "Saturday": "សៅរ៍",
    "Sunday": "អាទិត្យ",
    "Leave & Absence Requests": "សំណើសុំច្បាប់ និងអវត្តមាន",
    "Manage and approve teacher leave applications.": "គ្រប់គ្រង និងអនុម័តពាក្យសុំច្បាប់របស់គ្រូបង្រៀន។",
    "Apply Leave": "សុំច្បាប់",
    "Apply for Leave": "ដាក់ពាក្យសុំច្បាប់",
    "Leave Type": "ប្រភេទច្បាប់",
    "Sick Leave": "ច្បាប់ឈឺ",
    "Official Mission": "បេសកកម្មផ្លូវការ",
    "Annual Leave": "ច្បាប់ប្រចាំឆ្នាំ",
    "Personal Leave": "ច្បាប់ផ្ទាល់ខ្លួន",
    "Start Date": "ថ្ងៃចាប់ផ្ដើម",
    "End Date": "ថ្ងៃបញ្ចប់",
    "Reason / Notes": "មូលហេតុ / កំណត់សម្គាល់",
    "Reason for leave...": "បញ្ជាក់មូលហេតុនៃការសុំច្បាប់...",
    "Submit Leave Request": "ផ្ញើសំណើសុំច្បាប់",
    "Approved": "បានអនុម័ត",
    "Rejected": "បានបដិសេធ",
    "Pending": "រង់ចាំការពិនិត្យ",
    "Approve": "អនុម័ត",
    "Reject": "បដិសេធ",
    "No leave requests found.": "មិនទាន់មានសំណើសុំច្បាប់នៅឡើយទេ។",
    "Attendance Analytics & Heatmaps": "ការវិភាគ និងម៉ាទ្រីសវត្តមាន",
    "Institutional punctuality rankings, department metrics, and monthly heatmaps.": "ចំណាត់ថ្នាក់ភាពទៀងទាត់ ម៉ាទ្រីសតាមដេប៉ាតឺម៉ង់ និងគំនូសតាងវត្តមានប្រចាំខែ។",
    "Monthly Check-In Activity Matrix": "ម៉ាទ្រីសសកម្មភាពវត្តមានប្រចាំខែ",
    "Department Punctuality Ranking": "ចំណាត់ថ្នាក់ភាពទៀងទាត់តាមដេប៉ាតឺម៉ង់",
    "Most Active Teachers": "គ្រូបង្រៀនដែលមានវត្តមានច្រើនជាងគេ",
    "Punctuality Rate": "អត្រាភាពទៀងទាត់",
    "Check-Ins": "វត្តមានស្កែន",
    "check-ins": "វត្តមានស្កែន",
    "Check your attendance records instantly.": "ពិនិត្យមើលកំណត់ត្រាវត្តមានរបស់អ្នកភ្លាមៗ",
    "Today's Status": "ស្ថានភាពថ្ងៃនេះ",
    "Checked in at": "បានស្កែនចូលម៉ោង",
    "Checked out at": "បានស្កែនចេញម៉ោង",
    "Not checked in yet": "មិនទាន់បានស្កែននៅឡើយទេ",
    "On Duty": "កំពុងបំពេញភារកិច្ច",
    "Rate": "អត្រាវត្តមាន",
    "My QR Code": "កូដ QR របស់ខ្ញុំ",
    "Update Face ID": "ធ្វើបច្ចុប្បន្នភាពផ្ទៃមុខ",
    "Register Face ID": "ចុះឈ្មោះផ្ទៃមុខ",
    "Change PIN": "ផ្លាស់ប្តូរលេខកូដ PIN",
    "Logout": "ចាកចេញ",
    "Teacher Portal": "ច្រកទ្វារគ្រូបង្រៀន",
    "School Info": "ព័ត៌មានសាលា",
    "Pending Corrections": "ការកែប្រែដែលរង់ចាំ",
    "View Recent Chat IDs": "មើល Chat ID ថ្មីៗ",
    "Toggle Theme": "ផ្លាស់ប្តូរប្រធានបទ",
    "Sign Out": "ចាកចេញ",
    "All rights reserved.": "រក្សាសិទ្ធិគ្រប់យ៉ាង។",
    "Phnom Penh": "ភ្នំពេញ",
    "Present": "វត្តមាន",
    "Late": "យឺត",
    "Absent": "អវត្តមាន",
    "Holiday": "ថ្ងៃឈប់សម្រាក",
    "Morning Shift": "វេនព្រឹក",
    "Afternoon Shift": "វេនរសៀល",
    "Late after": "យឺតបន្ទាប់ពីម៉ោង",
    "Enable Telegram Alerts": "បើកការជូនដំណឹងតាម Telegram",
    "Receive instant notifications on check-in & check-out.": "ទទួលការជូនដំណឹងភ្លាមៗនៅពេលស្កែនចូល និងចេញ។",
    "Connect": "ភ្ជាប់ទំនាក់ទំនង",
    "Telegram Alerts Active": "ការជូនដំណឹង Telegram កំពុងដំណើរការ",
    "Your account is connected to @": "គណនីរបស់អ្នកបានភ្ជាប់ទៅកាន់ @",
    "Active": "សកម្ម",
    "Change": "ផ្លាស់ប្តូរ",
    "Export CSV": "ទាញយក CSV",
    "Dispute / Correct": "ស្នើសុំកែតម្រូវវត្តមាន",
    "Upcoming Holidays": "ថ្ងៃឈប់សម្រាកខាងមុខ",
    "Recent 30 Days": "ប្រវត្តិ ៣០ ថ្ងៃចុងក្រោយ",
    "Morning": "ព្រឹក",
    "Afternoon": "រសៀល",
    "LATE": "យឺត",
    "No records found in last 30 days.": "មិនមានកំណត់ត្រាក្នុងរយៈពេល ៣០ ថ្ងៃចុងក្រោយទេ។"
}

translations.update(system_wide_km)

with open(km_file, 'w', encoding='utf-8') as f:
    json.dump(translations, f, ensure_ascii=False, indent=4)

print("Updated km.json with full system translations:", len(system_wide_km), "keys.")
